const sequelize = require('../config/database');
const User = require('./user.model');
const Survey = require('./survey.model');
const Question = require('./question.model');
const QuestionOption = require('./questionOption.model');
const Response = require('./response.model');
const Answer = require('./answer.model');
const Attachment = require('./attachment.model');
const Log = require('./log.model');
User.hasMany(Survey, { foreignKey: 'user_id', as: 'surveys', onDelete: 'CASCADE' }); Survey.belongsTo(User, { foreignKey: 'user_id', as: 'creator' });
Survey.hasMany(Question, { foreignKey: 'survey_id', as: 'questions', onDelete: 'CASCADE' }); Question.belongsTo(Survey, { foreignKey: 'survey_id', as: 'survey' });
Question.hasMany(QuestionOption, { foreignKey: 'question_id', as: 'options', onDelete: 'CASCADE' }); QuestionOption.belongsTo(Question, { foreignKey: 'question_id', as: 'question' });
Survey.hasMany(Response, { foreignKey: 'survey_id', as: 'responses', onDelete: 'CASCADE' }); Response.belongsTo(Survey, { foreignKey: 'survey_id', as: 'survey' });
User.hasMany(Response, { foreignKey: 'user_id', as: 'responses', onDelete: 'SET NULL' }); Response.belongsTo(User, { foreignKey: 'user_id', as: 'user' });
Response.hasMany(Answer, { foreignKey: 'response_id', as: 'answers', onDelete: 'CASCADE' }); Answer.belongsTo(Response, { foreignKey: 'response_id', as: 'response' });
Question.hasMany(Answer, { foreignKey: 'question_id', as: 'answers' }); Answer.belongsTo(Question, { foreignKey: 'question_id', as: 'question' });
Attachment.hasMany(Answer, { foreignKey: 'file_id', as: 'answers' }); Answer.belongsTo(Attachment, { foreignKey: 'file_id', as: 'file' });
User.hasMany(Attachment, { foreignKey: 'uploaded_by', as: 'attachments' }); Attachment.belongsTo(User, { foreignKey: 'uploaded_by', as: 'uploader' });
User.hasMany(Log, { foreignKey: 'user_id', as: 'logs', onDelete: 'SET NULL' }); Log.belongsTo(User, { foreignKey: 'user_id', as: 'user' });
module.exports = { sequelize, User, Survey, Question, QuestionOption, Response, Answer, Attachment, Log };
